### PR TITLE
add sum-salaries solution

### PR DESCRIPTION
**Pull request by 11un**
Added solution from sandbox and one-liner option using reduce.

### CODE REVIEW

**Comment by iliakan** [comment]
Please remove extra indentation from inside ```.

Also, Object.values and reduce are explained at this point, you sure? :)

**Comment by 11un** [comment]
> Please remove extra indentation from inside ```.
Ok sorry, I need to figure where my formatting is incorrect when doing these. I've tried to replicate the other example solutions exactly. It may be related to my env / tools linux / vim / eslint / prettier etc. I'll look into it more soon and try again. 

> Also, Object.values and reduce are explained at this point, you sure? :)

Yes, Object.values, entries, etc. was in previous chapter (https://javascript.info/keys-values-entries) and used in the preexisting destructuring assignment example with the for.. of loop.

Also yes, reduce/reduce right is covered a few chapters back in the Array methods.. (https://javascript.info/array-methods)

**Comment by iliakan** [comment]
Thanks, actually extra indent is not a problem, scripts handle it well.

But it's really unnecessary =)

**Comment by 11un** [comment]
> Thanks, actually extra indent is not a problem, scripts handle it well.
> 
> But it's really unnecessary =)

Fixed it, and for moving forward... It was a md/eslint config lint-on-save setting used for an unrelated use-case and I also don't like the extra indentation in most cases. Here is the fixed: https://github.com/iliakan/javascript-tutorial-en/pull/772

**Pull request closed without merging**
