### PR TITLE
An addition to solution

### PR DESCRIPTION
**Pull request by Ghost-017**

### CODE REVIEW

**Comment by iliakan** [comment]
The task mentions no borders, the addition purpose is unclear. 
I understand what you mean, but that's actually confusing.

**Comment by Ghost-017** [comment]
Oh ok, I thought I was going to find the scrollbar width in an element because the examples were always revolved around an element. So the scrollbar in an entire document completely slipped my mind. Perhaps changing the title to, "What is the scrollbar width of the document?".

**Comment by iliakan** [comment]
The task is to find the scrollbar width of an element.

Not the "scrollWidth".

**Comment by Ghost-017** [comment]
I know, width not height.

**Pull request closed without merging**
