### PR TITLE
solution out of tutorial

### PR DESCRIPTION
**Pull request by maurodibert**
I've took the text and update the task file also!

### CODE REVIEW

**Comment by iliakan** [comment]
Why copy-pasting the solution from sandbox?

**Comment by maurodibert** [comment]
Because every other exercise has the solution on the same tutorial and it's really annoying, for instance, if you read the tutorial in a Kindle or you have not the possibility of opening the sandbox, to not see the solution.

**Comment by iliakan** [comment]
Then we need to change the code that represents the solution in e-book, not copy-paste it around.

**Comment by maurodibert** [comment]
Oh, sorry! I didn't think like that. First, I've just copy/paste not for laziness, hehe, but because the solution is correct and it's like other exercises (that I've suggested a copy/paste from sandbox).

Again, apologies if I do pull stupid suggestions but I'm really a newbie and want to contribute to your work that I love and think it's hell awesome!

**Pull request closed without merging**
