### PR TITLE
correct mdn link url

### PR DESCRIPTION
**Pull request by lilifan**
Sorry i don't know your link syntax , so i just add the full url

### CODE REVIEW

**Comment by iliakan** [comment]
Fixed thanks!

**Comment by lilifan** [comment]
Could you plz tell me how your special markdown url link syntax works ? @iliakan 
By the way, thanks for your great work!  I will try to translate some articles to your Chinese repository .

**Comment by iliakan** [comment]
That was actually custom feature of the site, to shorten links to MDN, not a markdown thing. =)

**Comment by lilifan** [comment]
got it, thank you for your reply~

**Pull request closed without merging**
