### PR TITLE
Update solution.md

### PR DESCRIPTION
**Pull request by maurodibert**
Please, tell me if it is still OK that I propose this on the exercises I discover through the tutorial.

### CODE REVIEW

**Comment by maurodibert** [comment]
And I'm thinking if you tell me how and give me instructions to follow, I could do it; that could be less annoying for you than reading "out of tutorial" various times! hehe

**Comment by iliakan** [comment]
Okay, let's do it like this: I'll make a variant and you tell me how good it is ;)
You know how to git checkout a branch? Can run the tutorial locally?

**Comment by maurodibert** [comment]
Great! And I think I could!

**Comment by maurodibert** [comment]
Ilya, hi! Just to check: you didn't do the new branch yet don't you?

**Comment by iliakan** [comment]
Took some time to manually check all tasks, some already had solution embedded.

Now all ok?

**Comment by maurodibert** [comment]
Wow, there were a lot! hehe. Great now! 💪

**Pull request closed without merging**
