### PR TITLE
Don't need arrow function here

### PR DESCRIPTION
**Pull request by friendlyanon**
The signature of `setTimeout` is:
```js
setTimeout(function[, delay, param1, param2, ...]);
```
https://devdocs.io/dom/windoworworkerglobalscope/settimeout

### CODE REVIEW

**Comment by welkin25** [comment]
maybe fix the settimeout-setinterval page as well for the same issue? Or should that be a separate PR?

**Comment by friendlyanon** [comment]
Actually, I went thru a lot of code and there are an unreasonable amount of arrow functions used in places where it is absolutely unnecessary, if not a waste.

**Comment by iliakan** [comment]
That setTimeout notation was created prior to arrow functions.

It's terrible actually. Not obvious at all.

**Comment by iliakan** [comment]
Think yourself, that's crazy - put function parameters aside from the function.

**Comment by friendlyanon** [comment]
List of builtins using this kind of function signature:

- https://devdocs.io/dom/windoworworkerglobalscope/settimeout
- https://devdocs.io/dom/windoworworkerglobalscope/setinterval
- https://devdocs.io/node/timers#timers_setimmediate_callback_args
- https://devdocs.io/node/process#process_process_nexttick_callback_args

It'd be best for a community curated resource for learning to highlight these kinds of things.
I've inherited too many codebases to work on where the previous person used
```js
process.nextTick(() => someFunc(arg1, arg2, arg3));
```
instead of properly making use of the builtin and writing
```js
process.nextTick(someFunc, arg1, arg2, arg3);
```

It's also a very obvious vararg pattern. Clarity in the proper usecases for the builtins is maintained.

**Comment by iliakan** [comment]
Nah, the latter notation was created only for performance.

I mean `process.nextTick(someFunc, arg1, arg2, arg3);`.
Not for clarity, for performance only.

**Comment by iliakan** [comment]
And also please re-read my message again, I was talking about setInterval/setTimeout.

Don't mess in process.nextTick please.

**Pull request closed without merging**
