### PR TITLE
Added Atom to IDE list

### PR DESCRIPTION
**Pull request by mittalyashu**
Added Atom to list of IDE.

### CODE REVIEW

**Comment by iliakan** [comment]
Sorry no much use among my friends. Removed Komodo though.

**Comment by mittalyashu** [comment]
I have added atom instead of Komodo

**Comment by iliakan** [comment]
There is atom there already =). Not atom IDE.

**Comment by mittalyashu** [comment]
But I think Atom and Atom IDE is different.

**Pull request closed without merging**
