### PR TITLE
Minor grammar changes to help improve flow.

### PR DESCRIPTION
**Pull request by gwooly**
Kept it as concise as possible whilst making it more readable. If happy with the adaptation then I'll do similar for the rest of the content.

### CODE REVIEW

**Comment by jmbothe** [comment]
Hi @gwooly Nice work. Let me know if you plan to go ahead with editing the rest of the content. I was working on editing the content as well, but if you decide you want to move forward, I will move on to other projects. Cheers!

**Comment by iliakan** [comment]
@jmbothe tired so soon? :)

**Comment by jmbothe** [comment]
Hahaha. @iliakan Never! It's just that my free time is very limited, and I don't want to be doing redundant work. I try to make every moment of my free time as useful as possible, and I don't think two people need to be working on this task (or, rather, if there are two or more people working on this task, I don't need to be one of them. Hahaha!).  I'll move forward based on @gwooly decision. I'm happy either way.

**Comment by gwooly** [comment]
Hey guys. @jmbothe I'll happily go through the rest of the content in its entirety - I'm still using it as a resource myself so if anything it's mutually beneficial as I get to read through several times, and you can put your time toward other interests!

**Comment by jmbothe** [comment]
@gwooly Cool. Thanks. Holler at me if you change your mind. I can pick up wherever you leave off. cheers!

**Pull request merged**
