### PR TITLE
Update article.md

### PR DESCRIPTION
**Pull request by maurodibert**
Moving to the very first place that occurred an added a little bit more of information about.

### CODE REVIEW

**Comment by iliakan** [comment]
No, sorry, that should be after. That's like P.S.

We should be using strict all the time.

**Comment by maurodibert** [comment]
Hi Ilya! But P.S. it's at the end of the section?

**Comment by iliakan** [comment]
it's right at the end of the article section, before ## Object.defineProperties

**Comment by maurodibert** [comment]
Yeap! I saw there but what I wanted to say is that if it's mandatory for PS´s, to go at the end. PS = info boxes. Because if not, when you first try the exercise, do not know why it doesn't throw an error.

Oh, and would be great to explain on the 'strict mode' chapter, what happens with chrome console.

**Comment by iliakan** [comment]
I added use strict for console there.

**Comment by maurodibert** [comment]
Ahhh! Understood now! 👍  Awesome!

**Pull request closed without merging**
