### PR TITLE
Update article.md

### PR DESCRIPTION
**Pull request by LinkChef**
Changed gender pronouns, did it for the whole page since I didn't see all of them at first.

### CODE REVIEW

**Comment by iliakan** [comment]
So "visitor" is "they"? Why? :)

**Comment by IanWitham** [comment]
"They" is more inclusive and doesn't presume gender. Of course a hypothetical visitor _could_ be a "he", but that's rather a silly argument. Altering the language slightly would make this tutorial more welcoming to _everyone_, not just men.

The tutorial has a really modern look and feel, which is good, but the inclusion of outdated sexist language seems an odd contrast to say the least.

**Comment by iliakan** [comment]
Okay okay I'm outdated. Thanks! :)

**Comment by LinkChef** [comment]
Thank you for the merge!  I did want to explain that the reason I did ask for the change is specifically because I know people could be offended by it, even if I am not.  Especially for a website that's really high up the search term, I wanted this to be good for a wide audience, especially since this is such a good tutorial.

Thanks for the merge!

**Comment by iliakan** [comment]
Thanks you for the PR, your change is really good! 👍

**Pull request merged**
