### PR TITLE
Update article.md

### PR DESCRIPTION
**Pull request by maurodibert**
I think it could be easier to grasp it with these small changes:
- _the counter_ is the global concept
- `count` is the variable
Since they are too similar, it gets messy (at least in my brain! hehe).

(and I was studying, founded this and came here but now I will continue with what you've done yesterday! 💪)

### CODE REVIEW

**Comment by iliakan** [comment]
Right, that was a typo, thank you! (merged manually due to local changes)

**Comment by maurodibert** [comment]
Hi Ilya! Where could I write to you for asking for some things related to the tutorial but not directly related to this specifically?

**Comment by iliakan** [comment]
Tell me.

**Comment by maurodibert** [comment]
Great! 

Here we have the freeCodeCamp Community and JS Community which are cool, give free random lessons, etc but it's not that organized. I really want to give a free weekly course on basics since I'm too a newbie and thought on a weekly study from your material, which I think it's the only one I've studied that's so perfectly organized and goes step by step to the roots.

The thing is that there a lot of people here (even advanced), that do not know the basis and also do not know English to learn those. So I thought to translate the tutorial for them and at the same time if you give me the permission and if you want, translate the tutorial for the web to Spanish.

It's gonna be an amazing opportunity for me to learn more and for the people here to learn to go to the deepness of study (a thing that we're not used to! hehe) and at the same time, give to the tutorial the possibility to reach more people.

Thanks again for your time!

**Comment by iliakan** [comment]
Sure, Spanish is a great language, a lot of people speak it.
Did you look at https://github.com/iliakan/javascript-tutorial-en/issues/754?

**Comment by maurodibert** [comment]
Oh awesome! And I did now ;-) Tks Ilya!

**Pull request closed without merging**
