### PR TITLE
Edit typos in article.md

### PR DESCRIPTION
**Pull request by aadithpm**

### CODE REVIEW

**Comment by iliakan** [comment]
What's wrong with 'From the other hand' ?

Are you a native speaker (if I may ask) ?

**Comment by aadithpm** [comment]
No, I'm not but my English is decent. Also, the expression that is usually used is 'on the other hand'. I haven't heard of 'from the other hand' used in that context. 

That being said, it's a simple grammatical error and doesn't affect what's being put across in anyway so it's pretty minor.

**Comment by iliakan** [comment]
I hope a native speaker will look at the PR and give a feedback.

If you are reading this -- please, do :)

**Comment by iliakan** [comment]
Made some research, I think you're right, thank you, merging in!

**Comment by aadithpm** [comment]
Haha, no problem man. Always happy to help.

**Pull request merged**
