### PR TITLE
Remove the redundant argument

### PR DESCRIPTION
**Pull request by shihaoli**
This tutorial is awesome! I just think the argument of this[method] is redundant in this case.

### CODE REVIEW

**Comment by iliakan** [comment]
Yeah, but generally it's not redundant, just not used here. Let's leave it :)

**Comment by shihaoli** [comment]
```javascript
    handleEvent(event) {
      // mousedown -> onMousedown
      let method = 'on' + event.type[0].toUpperCase() + event.type.slice(1);
      this[method]();
    }

    onMousedown() {
      elem.innerHTML = "Mouse button pressed";
      console.log('event1', event.type)
    }

    onMouseup() {
      elem.innerHTML += "...and released.";
              console.log('event2', event.type)
    }
  }
```

**Comment by iliakan** [comment]
That's bad practice. Don't use global event object.

**Comment by shihaoli** [comment]
```javascript
 class Menu {
    handleEvent(event) {
      // mousedown -> onMousedown
      let method = 'on' + event.type[0].toUpperCase() + event.type.slice(1);
      this[method](event);
      console.log('event1',event.target) // event 1 <button id="elem">Mouse button pressed...and released.</button>
    }

    onMousedown() {
      elem.innerHTML = "Mouse button pressed";
      console.log('event2',event.target)
    }

    onMouseup() {
      elem.innerHTML += "...and released.";
      console.log('event3',event.target)
    }
  }

  let menu = new Menu();
  elem.addEventListener('mousedown', menu);
  elem.addEventListener('mouseup', menu);
```

**Pull request closed without merging**
