### PR TITLE
Update syntax / grammar of 2-code-editors

### PR DESCRIPTION
**Pull request by imidom**
Please note that "Visual Studio Code" is listed as both an IDE and a lightweight editor. I think this is being discussed [here](https://github.com/iliakan/javascript-tutorial-en/pull/534).

### CODE REVIEW

**Comment by iliakan** [comment]
Please remove it from lightweight editors and leave only in IDE then? :)

**Comment by imidom** [comment]
It sounds like the people discussing this on the other PR linked above felt like VS Code should be moved under lightweight editor, not IDE. I'm not an expert on this, so just tell me where you think it should go. Is VS Code more of a lightweight editor or an IDE? #534

**Comment by iliakan** [comment]
It's quite lightweight. And it has many IDE features.

**Comment by imidom** [comment]
How do you feel about keeping it under the lightweight section, but mentioning it has many IDE features as well?

**Comment by imidom** [comment]
Updated!

**Pull request merged**
