### PR TITLE
Solution out of tutorial

### PR DESCRIPTION
**Pull request by maurodibert**
Hi! Same case as before. I keep thinking it's useful to have solutions on the same web page. Since you've closed the last one, I'm not sure if I'm explaining the whys correctly.

### CODE REVIEW

**Comment by iliakan** [comment]
Did you copy-paste it?

**Comment by maurodibert** [comment]
Hi! I use the solution and added the first part. Which would be the correct procedure?

**Comment by iliakan** [comment]
What's the purpose of copying the solution? To avoid extra click to sandbox?

**Comment by maurodibert** [comment]
It does not just avoid the extra click but there are situations and devices that don't allow the sandbox. And beyond that, I really don't see consistency with some exercises in the sandbox and the whole rest in the tutorial. Why isn't everything in just one place and the one you're working on?

**Comment by iliakan** [comment]
@bezart please take a look.

**Comment by iliakan** [comment]
I'll try to embed plunker.

**Comment by maurodibert** [comment]
Ilian! Great! And now you said about embed plunker, I've understood what you've said about copy/paste! 🤦‍♂

**Pull request closed without merging**
